### ISSUE TITLE
Proxy error: Could not proxy request /api/v1/transactions from localhost:3000 to http://localhost:5000.

### ISSUE THREAD

**Issue by Aman7400** [bradtraversy/expense-tracker-mern#10]

**Comment by znation92** [comment]
these steps solved the issue for me. give it a try

1. install the dependencies in both the main project folder and the client folder
2. make sure your mongoDB is running, 
3. add your localhost Db uri to the config.env file which is most likely <mongodb://localhost:27017/nameofapp>

**Comment by deepankijain** [comment]
Install cors in server side and use it in server js. And make sure both servers are running.

**Comment by harshbhandariv** [comment]
[stackoverflow](https://stackoverflow.com/a/57532447/12800484)
This should solve your issue.

**Comment by trilionit** [comment]
> [stackoverflow](https://stackoverflow.com/a/57532447/12800484)
> This should solve your issue.

Had a similar issue in the past and this solved it for me.

**Comment by frolicSandy** [comment]
I was stuck at the same error for a while and none of these solutions seemed to work for me. The error message I was getting is as follows:
`Error: connection <monitor> to 15.206.200.5:27017 closed`
`[nodemon] app crashed - waiting for file changes before starting...`
`Proxy error: Could not proxy request /api/v1/transactions/ from localhost:3000 to http://localhost:5000/.`
`See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).`

**Solution:**
Add the following IP address to the IP Access list in MongoDB Atlas.
`0.0.0.0/0`
<br><br>
<i>Adding this comment just in case someone faces the issue similar to mine</i>
